services:
    _defaults:
        public: true

    Gigadrive\Bundle\MarkdownWikiBundle\:
        autowire: true
        autoconfigure: true
        resource: '../../*'
        exclude: '../../{DependencyInjection,Constants,Model,Entity,MarkdownWikiBundle.php,Service/MarkdownWikiImporter.php}'

    markdownwiki.parser:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiParser

    markdownwiki.importer:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiImporter
        arguments:
            - ''
            - '@markdownwiki.parser'
            - '@logger'

    markdownwiki.storage.file:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\Storage\FileMarkdownWikiStorage

    markdownwiki.storage:
        alias: markdownwiki.storage.file

    Gigadrive\Bundle\MarkdownWikiBundle\Service\Storage\MarkdownWikiStorageInterface:
        alias: markdownwiki.storage