services:
    Gigadrive\Bundle\MarkdownWikiBundle\Service:
        resource: '../../Service/*'
        autowire: true
        autoconfigure: true

    markdownwiki.parser:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiParser
