services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Gigadrive\Bundle\MarkdownWikiBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Constants,Entity,MarkdownWikiBundle.php}'

    markdownwiki.parser:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiParser
