services:
    _defaults:
        public: true

    Gigadrive\Bundle\MarkdownWikiBundle\:
        autowire: true
        autoconfigure: true
        resource: '../../*'
        exclude: '../../{DependencyInjection,Constants,Model,Entity,MarkdownWikiBundle.php,Service/MarkdownWikiImporter.php}'

    markdownwiki.parser:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiParser

    Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiParser:
        alias: markdownwiki.parser

    markdownwiki.importer:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiImporter
        arguments:
            - ''
            - '@markdownwiki.parser'
            - '@logger'

    Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiImporter:
        alias: markdownwiki.importer

    markdownwiki.storageservice:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\MarkdownWikiStorageService
        arguments:
            - '@markdownwiki.storage'
            - '@markdownwiki.importer'
            - '@logger'

    markdownwiki.storage.file:
        class: Gigadrive\Bundle\MarkdownWikiBundle\Service\Storage\FileMarkdownWikiStorage
        arguments:
            - '@kernel'

    markdownwiki.storage:
        alias: markdownwiki.storage.file

    Gigadrive\Bundle\MarkdownWikiBundle\Service\Storage\MarkdownWikiStorageInterface:
        alias: markdownwiki.storage